default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails
  password: cafeehbom
  host: 206.189.190.11
  port: 5432
 
development:
  <<: *default
  database: luciosx_development
  
test:
  <<: *default
  database: luciosx_test
 
production:
  <<: *default
  database: find_my_coffee_api_production
  username: find_my_coffee_api
  password: <%= ENV['FIND_MY_COFFEE_API_DATABASE_PASSWORD'] %>
